// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezivlsoowcuubuyfwkgg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6aXZsc29vd2N1dWJ1eWZ3a2dnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMTMxMjQsImV4cCI6MjA2NzU4OTEyNH0.5m4lXZbcVyGk3sNhi59H6g2Pt5dOKgjm0ntgK9Gnx2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});